### ISSUE TITLE
Production Implementation

### ISSUE THREAD

**Issue by egkelly** [spiffe/spire-controller-manager#100]
Is there a plan or goal in place to migrate this project from pre-prod to production?

**Comment by azdagron** [comment]
My personal checklist would be to finish up #149 and #122 and let those bake for a bit, particularly from the perspective of folks migrating from the old registrar. Once we have some confidence that those features are solid, we'll be in a good position to begin running down the prod checklist and bring the project up for "production" status approval from the SPIFFE Steering Committee.
