### ISSUE TITLE
Disable namespaces by regex

### ISSUE THREAD

**Issue by faisal-memon** [spiffe/spire-controller-manager#161]
Allow for `ignoreNamespaces` [configurable](https://github.com/spiffe/spire-controller-manager/blob/main/docs/spire-controller-manager-config.md) to take a regex for namespaces to disable.

Ported over from https://github.com/spiffe/spire/issues/3386

**Comment by erikgb** [comment]
I would love to see this feature implemented.

**Comment by unnathik** [comment]
I'd like to work on this.
