### ISSUE TITLE
Handle SPIRE Server's that don't support hint/jwt-svid-ttl

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire-controller-manager#178]
The hint and jwt-svid-ttl fields are fairly new additions to the Entry SPIRE Server API. Therefore, when running against an older SPIRE server, these fields get ignored. The controller currently tries to update entries with these fields every reconciliation loop since the hint/jwt-svid-ttl fields were not retained.

We need to decide what do to here. A few options:
1. Crash if SPIRE server does not support all of the fields
2. Ignore fields not supported by SPIRE server for reconciliation

(1) is ideal, except that we then have to come up with a support SPIRE server matrix, and we have the potential to disrupt existing deployments. Another point to consider is that hint and jwt-svid-ttl fields are not commonly set. It might be a shame to force everyone to upgrade SPIRE server for no (perceived) benefit.
(2) has the downside of an operator being potentially confused why those fields aren't being honored.

**Comment by matthewdevenny** [comment]
What if you just captured that as a warning event on the resource? That way if someone is trying to figure out why its not being honored using `kubectl describe` would show them an appropriate warning event
