### ISSUE TITLE
Entry reconciler deletes entries corresponding to join tokens

### ISSUE THREAD

**Issue by shashankram** [spiffe/spire-controller-manager#247]
The entry reconciler deletes registration entries corresponding to join tokens. Due to this, any join tokens created on the server managed by the controller is unusable. Should there be an exception to entries corresponding to join tokens in the entry reconciler? We could potentially avoid cleanup of join token entries by ensuring entries whose parent SPIFFE ID contains `/spire/agent/join_token/` aren't reconciled.

**Comment by azdagron** [comment]
The SPIRE Controller Manager made an early assumption that all agents would be joining via PSAT (and relies on this when parenting entries for workloads). Curious what the use case is for agents joining via join tokens.

**Comment by shashankram** [comment]
In on-prem environments where agents are running outside k8s, we use join tokens for attestation. This is because we can't leverage any of the platform specific attestors. With the introduction of `ClusterStaticEntry`, we should be able to attest agents that are running in environments external to k8s even if the controller and server are running in k8s.

**Comment by MarcosDY** [comment]
unfortunatly controller manager will clean any entry that is not managed by it, 
for this use case, can you use x509pop? that is not a platform specific attestor.

**Comment by shashankram** [comment]
x509pop isn't suitable for my use case. We want to use join tokens. Is there a reason the controller can't ignore entries corresponding to join tokens? Even if not by default, a config override would help.

**Comment by shashankram** [comment]
> x509pop isn't suitable for my use case. We want to use join tokens. Is there a reason the controller can't ignore entries corresponding to join tokens? Even if not by default, a config override would help.

@azdagron @MarcosDY what do you think of this?

**Comment by azdagron** [comment]
I think the overall request is reasonable. In terms of implementation, I think we'd want to get _very_ specific in ignoring specifically the novelty entries that map a join token agent to a SPIFFE ID.....

**Comment by shashankram** [comment]
> I think the overall request is reasonable. In terms of implementation, I think we'd want to get _very_ specific in ignoring specifically the novelty entries that map a join token agent to a SPIFFE ID.....

That makes sense. I noticed the entries corresponding to join tokens always have a parent ID containing the substring `/spire/agent/join_token/`. Would be it safe to filter out such entries prior to deletion in the entry reconciler?

**Comment by azdagron** [comment]
I think we'd have to do that in combination with also checking for the presence of the spiffe_id selector. There is nothing preventing someone from using a ClusterStaticEntry to parent something to a join token node directly.

**Comment by shashankram** [comment]
> I think we'd have to do that in combination with also checking for the presence of the spiffe_id selector. There is nothing preventing someone from using a ClusterStaticEntry to parent something to a join token node directly.

Makes sense. I'll try to create a PR for this soon.

**Comment by shashankram** [comment]
@azdagron @MarcosDY created a PR for this https://github.com/spiffe/spire-controller-manager/pull/306

**Comment by kfox1111** [comment]
This could also be solved by a 'managedby' field.
