### ISSUE TITLE
Entries keep getting re-created in a loop causing SDS warnings

### ISSUE THREAD

**Issue by alexandrealvino** [spiffe/spire-controller-manager#31]
Unexpected behavior from controller-manager that causes re-creation of entries in a loop, generating the following warning when using Envoy SDS API:

`2022-07-11T15:36:18.747976Z	warning	envoy config	StreamSecrets gRPC config stream closed: 3, unable to retrieve all requested identities, missing map[default:true]` 

This leads to a brief state that there is no identities available for attested workloads.

**Comment by azdagron** [comment]
Thanks for reporting this @alexandrealvino! I've identified the bug that resulted in the controller manager recreating all entries on every reconciliation.
