### ISSUE TITLE
Service DNS names should be automatically populated

### ISSUE THREAD

**Issue by sjberman** [spiffe/spire-controller-manager#48]
The k8s-workload-registrar had a flag that would tell it to populate DNS names of Services for a Pod (`service-name.namespace.svc`). This is an important DNS name to be included in a certificate since connections between Pods tend to go through the Services themselves. I send traffic to a Service, not a Pod.

There is a workaround suggested to use the `app` label as a dns name template: 
```
dnsNameTemplates: ["{{ index .PodMeta.Labels \"app\" }}.{{ .PodMeta.Namespace }}.svc.cluster.local"]
```
however we can't necessarily rely on a user to use this exact label. There are many labels that are common to k8s for matching selectors, and a user could also choose to use whatever label they want. We can't constrain that.

It would be nice if this field was configurable as well, since the suggestion includes `.cluster.local` but we may not want that suffix. Or maybe the cluster DNS zone is different than the default.

**Comment by marcofranssen** [comment]
Looking for the same feature here as well.

IMHO following is what should happen.

- [ ] Reconcile endpoints that end up on a SPIFFE enabled pod.
- [ ] 🤔 Reconcile ingresses that end up on a SPIFFE enabled pod. (allow to use the certs for ingress)

**Comment by faisal-memon** [comment]
assign to me

**Comment by faisal-memon** [comment]
I have the changes ready in my fork: https://github.com/faisal-memon/spire-controller-manager/tree/48

It needs the cluster domain, so once https://github.com/spiffe/spire-controller-manager/pull/90 gets merged  then Ill put out a PR for auto populating dns names.
