### ISSUE TITLE
Support setting parentID using the CRD

### ISSUE THREAD

**Issue by keeganwitt** [spiffe/spire-controller-manager#54]
The CRD used by the Registrar allowed you to see the parentID in manually created entries (using the CRD). We should continue to support this, as it is particularly useful for use cases like creating entries in the primary server for downstream clusters that are on different K8s clusters.

**Comment by azdagron** [comment]
I believe this use case (entries for workloads outside of the cluster) is now covered by the ClusterStaticEntry CR.
