### ISSUE TITLE
Add support to JWT SVID Ttl

### ISSUE THREAD

**Issue by MarcosDY** [spiffe/spire-controller-manager#65]
Add support to JWT SVID TTL (jwt_svid_ttl) that  was introduced on [spire-api-sdk](https://github.com/spiffe/spire-api-sdk/commit/02f1e39e8856733f1353145d9b5812470f8619ec).

**Comment by drewwells** [comment]
Any progress on this?

**Comment by unnathik** [comment]
I'd like to work on this!
