### ISSUE TITLE
Allow for manually created entries

### ISSUE THREAD

**Issue by faisal-memon** [spiffe/spire-controller-manager#76]
Right now spire-controller-manager will automatically delete any entries that it didn't create. For more complex use cases we need the ability to manually create entries.

- A flag/namespace on auto generated entries. spire-controller-manager will only clean up entries with this flag set.
- A low level CRD similar to the [SpiffeID CRD from the k8s-workload-registrar](https://github.com/spiffe/spire/blob/main/support/k8s/k8s-workload-registrar/mode-crd/config/spiffeid.spiffe.io_spiffeids.yaml). spire controller-manager won't clean up entries attached to instances of this CRD.

Other ideas? Please comment below.

**Comment by kfox1111** [comment]
Can do this today with nesting. Only the spire server dedicated to spire-controller-manager gets its entries removed.

But more direct support for the use case would be nice.

**Comment by keeganwitt** [comment]
Capturing solution ideas from Slack:


1. Add a namespace dimension to the entries and keep the Registrar entries in their own namespace.
1. Add native support for Kubernetes to the SPIRE server. One way this could look is that the server handles the creation of SpiffeId K8s objects and the Registrar only handles watching for nodes/pods and invoking the server.
1. Use the bootstrap solution proposed in #76
1. Add a lineage label to entries to indicate how they got created.

**Comment by azdagron** [comment]
Thanks for capturing this @keeganwitt ❤️ We'll huddle and figure out the direction we think makes most sense for the project. There is definite consensus that we need to provide something in this space and ASAP. I appreciate the patience.

Also, sorry this discussion went to the sidelines. We have not done a good job of carving out time for these ancillary components in our regular discussions. We're discussing how we can do better.

**Comment by azdagron** [comment]
The proposal put forth by the maintainers is documented in issuer #149.

**Comment by keeganwitt** [comment]
> The proposal put forth by the maintainers is documented in issue #149.

Should we close this issue in favor of that one?

**Comment by azdagron** [comment]
This is covered by the ClusterStaticEntry CR.
