### ISSUE TITLE
workload svid not served even if pod is registered by controller manager

### ISSUE THREAD

**Issue by raffaelespazzoli** [spiffe/spire-controller-manager#87]
I have a pretty standard controller manager setup, copied from the example. From the log I can see that my pod is being reconciled:
```
2023-02-03T14:44:14Z DEBUG Triggering reconciliation {"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"ubi8-d88cc8448-qq6bn","namespace":"test-spire"}, "namespace": "test-spire", "name": "ubi8-d88cc8448-qq6bn", "reconcileID": "adcd3da7-6c49-4c36-8ce5-1d72f11dc9d0"}
```
when I try to get the svid for that pod I get the following error message
```
/opt/spire/bin/spire-agent api fetch -socketPath /spiffe-workload-api/agent.sock
rpc error: code = PermissionDenied desc = no identity issued
```
any suggestion on how to troubleshoot this?

**Comment by azdagron** [comment]
I would first check the SPIRE server and controller manager logs to see if the entry for that pod has been created. You can then inspect the agent logs to verify that it synced down the registration entry and also to see what happened when the workload was attested, i.e., what selectors were produced for the workload and how they line up with the selectors in the registration entry.

**Comment by raffaelespazzoli** [comment]
solved
