### ISSUE TITLE
Demo ControllerManagerConfig is invalid

### ISSUE THREAD

**Issue by egkelly** [spiffe/spire-controller-manager#99]
According to the [CRD](https://github.com/spiffe/spire-controller-manager/blob/main/config/crd/bases/spire.spiffe.io_controllermanagerconfigs.yaml) for ControllerManagerConfig, the [spire-controller-manager-config.yaml](https://github.com/spiffe/spire-controller-manager/blob/main/demo/config/cluster1/spire/spire-controller-manager-config.yaml) examples for both cluster1 and cluster2 are invalid. The spec is not built out to configure metrics, clustername, trustdomain, ignoreNamespaces etc.

**Comment by egkelly** [comment]
Ah, in looking closer at the demo, I realize kustomize is transforming the spire-controller-manager-config.yaml into a configmap. Why not create the yaml file as a configmap to begin with? This caused me a good deal of confusion 😃

**Comment by azdagron** [comment]
For better or worse, the ControllerManagerConfig (not a CRD, but a component config type) follows the pattern for custom controller configuration evangelized by the kubebuilder project (on which spire-controller-manager is built).

For more info: https://book.kubebuilder.io/component-config-tutorial/tutorial.html.

**Comment by azdagron** [comment]
If there is a change to how that config is applied that would be clearer; we'd welcome a PR with a suggested change :)
